//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Facturas
    {
        public int Id { get; set; }
        [Display(Name = "Cliente")]
        public string UsuarioId { get; set; }

        [DataType(DataType.Currency)]
        public decimal Importe { get; set; }

        public virtual Pedidos Pedido { get; set; }
    }
}
