//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedidos
    {
        public int Id { get; set; }

        [Display(Name = "Cliente")]
        public string UsuarioId { get; set; }

        public System.DateTime Fecha { get; set; }
        public int Cantidad { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Precio Total Pedido")]
        public decimal Total { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
