//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_CarritoCompra.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.PrecioUnidad = 0m;
        }

        public int Id { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Nombre demasido largo. Máximo permitido 50 caracteres")]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Descripción")]
        [MaxLength(150, ErrorMessage = "Descripción demasiada larga. Máximo permitido 150 caracteres")]
        public string Descripcion { get; set; }

        [DataType(DataType.Upload)]
        [Required(ErrorMessage = "Por favor seleccione una imagen.")]
        [Display(Name = "Imagen Producto")]
        //[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.jpg)$", ErrorMessage = "Únicamente ficheros con extensión .jpg")]
        public string PathImagen { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        [Display(Name = "Precio Unidad")]
        public decimal PrecioUnidad { get; set; }

        [Display(Name = "Categoría")]
        public virtual Categorias Categoria { get; set; }

        [Required(ErrorMessage = "Por favor seleccione una categoría.")]
        public int SelectedIdCategoria { get; set; }
        public SelectList SelectListCategorias { get; set; }

        public virtual Carrito ArticuloCarrito { get; set; }
    }
}
