INSERT INTO CATEGORIAS VALUES ('D.O.Ca. Rioja (La Rioja)','Denominación de Origen Calificada Rioja');
INSERT INTO CATEGORIAS VALUES ('D.O. Cava (Cataluña)','Denominación de Origen Cava');
INSERT INTO CATEGORIAS VALUES ('D.O. La Mancha (Castilla La Mancha)','Denominación de Origen La Mancha');
INSERT INTO CATEGORIAS VALUES ('D.O. Ribera del Duero (Castilla y León)','Denominación de Origen Ribera del Duero');
INSERT INTO CATEGORIAS VALUES ('D.O. Valdepeñas (Castilla La Mancha)','Denominación de Origen Valdepeñas');
INSERT INTO CATEGORIAS VALUES ('D.O. Valencia (Comunidad Valenciana)','Denominación de Origen Valencia');
INSERT INTO CATEGORIAS VALUES ('D.O. Rueda (Castilla y León)','Denominación de Origen Rueda');
INSERT INTO CATEGORIAS VALUES ('D.O. Cariñena (Aragón)','Denominación de Origen Cariñena');
INSERT INTO CATEGORIAS VALUES ('D.O.Ca Priorat (Priorat)','Denominación de Origen Calificada Priorat');
INSERT INTO CATEGORIAS VALUES ('D.O. Navarra (Navarra)','Denominación de Origen Navarra');